import { ToolDefinition } from '../types/tools';

export const ALL_TOOLS: ToolDefinition[] = [
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    tagline: 'Turn JPG, PNG and WEBP images into a professional PDF in seconds.',
    description: 'Combine and convert multiple images into a clean, high-resolution PDF document with custom page orientation, margins, and layout.',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    iconName: 'FileImage',
    path: '/tools/image-to-pdf',
    acceptedFileTypes: '.jpg,.jpeg,.png,.webp,.bmp',
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/bmp'],
    maxFiles: 30,
    badge: 'Popular',
    seoTitle: 'Image to PDF Online – Free Image to PDF Converter | CM DocFlow AI',
    seoDescription: 'Convert JPG, PNG and WEBP images to PDF online quickly and securely with CM DocFlow AI. No watermark, high quality.'
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    tagline: 'Convert DOC and DOCX documents to standard PDF format instantly.',
    description: 'Transform Microsoft Word documents into universally readable PDF files with preserved formatting and typography.',
    category: 'conversion',
    categoryLabel: 'Conversion Tools',
    iconName: 'FileText',
    path: '/tools/word-to-pdf',
    acceptedFileTypes: '.docx,.doc',
    acceptedMimeTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword'],
    maxFiles: 5,
    seoTitle: 'Word to PDF Converter – Convert DOCX to PDF Online | CM DocFlow AI',
    seoDescription: 'Accurately convert DOCX and DOC files to PDF online with CM DocFlow AI. Fast, secure, and preserves document structure.'
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    tagline: 'Extract PDF pages into pristine high-resolution JPG, PNG or WEBP.',
    description: 'Convert every page or selected pages of any PDF into crystal-clear images, downloadable individually or as a single ZIP archive.',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    iconName: 'ImageDown',
    path: '/tools/pdf-to-image',
    acceptedFileTypes: '.pdf',
    acceptedMimeTypes: ['application/pdf'],
    maxFiles: 1,
    seoTitle: 'PDF to Image Converter – Convert PDF to JPG, PNG, WEBP | CM DocFlow AI',
    seoDescription: 'Extract PDF pages into JPG, PNG or WEBP images with adjustable DPI and crisp clarity. Batch download as ZIP.'
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    tagline: 'Reduce PDF file size without sacrificing readability.',
    description: 'Shrink oversized PDF documents with smart compression presets (Low, Medium, High) for easy emailing and rapid sharing.',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    iconName: 'Minimize2',
    path: '/tools/pdf-compressor',
    acceptedFileTypes: '.pdf',
    acceptedMimeTypes: ['application/pdf'],
    maxFiles: 5,
    badge: 'Essential',
    seoTitle: 'Compress PDF Online – Reduce PDF File Size | CM DocFlow AI',
    seoDescription: 'Compress PDF files online for free. Choose compression level and view exact megabytes saved. Fast and browser-secure.'
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    tagline: 'Combine multiple PDF files into one unified document.',
    description: 'Effortlessly merge PDFs in your desired order. Reorder pages and files with intuitive drag-and-drop controls.',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    iconName: 'Layers',
    path: '/tools/merge-pdf',
    acceptedFileTypes: '.pdf',
    acceptedMimeTypes: ['application/pdf'],
    maxFiles: 20,
    badge: 'Popular',
    seoTitle: 'Merge PDF Online – Combine PDF Files Free | CM DocFlow AI',
    seoDescription: 'Merge multiple PDF documents into one PDF file online. Reorder files visually and download in seconds.'
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    tagline: 'Separate one PDF into individual pages or specific page ranges.',
    description: 'Split PDF files by custom ranges (e.g. 1-3, 4-7) or burst each page into distinct files bundled in a convenient ZIP archive.',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    iconName: 'Scissors',
    path: '/tools/split-pdf',
    acceptedFileTypes: '.pdf',
    acceptedMimeTypes: ['application/pdf'],
    maxFiles: 1,
    seoTitle: 'Split PDF Online – Separate PDF Pages & Ranges | CM DocFlow AI',
    seoDescription: 'Extract specific page ranges or split every page from your PDF into separate files with CM DocFlow AI.'
  },
  {
    id: 'pdf-page-extractor',
    name: 'PDF Page Extractor',
    tagline: 'Pick and extract only the exact pages you need from any PDF.',
    description: 'Visually select the pages you want to keep and generate a streamlined PDF containing only your selected pages.',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    iconName: 'Copy',
    path: '/tools/pdf-page-extractor',
    acceptedFileTypes: '.pdf',
    acceptedMimeTypes: ['application/pdf'],
    maxFiles: 1,
    seoTitle: 'Extract PDF Pages Online – Free Page Extractor | CM DocFlow AI',
    seoDescription: 'Select and export specific pages from any PDF document into a new compact PDF. Free, fast and private.'
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    tagline: 'Convert PDF documents into editable Word (DOCX) files.',
    description: 'Extract text, paragraphs, and document structure from PDFs to create clean, fully editable Word documents.',
    category: 'conversion',
    categoryLabel: 'Conversion Tools',
    iconName: 'FileSpreadsheet',
    path: '/tools/pdf-to-word',
    acceptedFileTypes: '.pdf',
    acceptedMimeTypes: ['application/pdf'],
    maxFiles: 5,
    badge: 'Pro Favorite',
    seoTitle: 'PDF to Word Converter – Convert PDF to Editable DOCX | CM DocFlow AI',
    seoDescription: 'Convert PDF to editable DOCX format online. Maintain text flow and typography with CM DocFlow AI.'
  },
  {
    id: 'image-format-converter',
    name: 'Image Format Converter',
    tagline: 'Universal image workshop: Convert JPG, PNG, WEBP with custom quality.',
    description: 'Convert between any modern image formats in batches with custom resolution scaling, compression level, and quality controls.',
    category: 'image',
    categoryLabel: 'Image Tools',
    iconName: 'RefreshCw',
    path: '/tools/image-format-converter',
    acceptedFileTypes: '.jpg,.jpeg,.png,.webp,.bmp,.gif',
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/bmp', 'image/gif'],
    maxFiles: 25,
    seoTitle: 'Image Format Converter Online – Convert JPG, PNG, WEBP | CM DocFlow AI',
    seoDescription: 'Universal image format conversion with resolution scaling, aspect ratio preservation, and batch downloads.'
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    tagline: 'Compress JPG, PNG and WEBP photos with up to 90% size reduction.',
    description: 'Intelligent compression that removes unnecessary image payload while keeping visuals sharp for web performance.',
    category: 'image',
    categoryLabel: 'Image Tools',
    iconName: 'FileArchive',
    path: '/tools/image-compressor',
    acceptedFileTypes: '.jpg,.jpeg,.png,.webp',
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxFiles: 20,
    badge: 'Fast',
    seoTitle: 'Image Compressor Online – Compress JPG, PNG, WEBP | CM DocFlow AI',
    seoDescription: 'Reduce image file size without perceptible loss of quality. Batch compress and download as ZIP.'
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    tagline: 'Convert JPG pictures into lossless PNG format with transparency ready.',
    description: 'One-click dedicated conversion from JPG to crisp PNG format for web graphics and design projects.',
    category: 'image',
    categoryLabel: 'Image Tools',
    iconName: 'ArrowRightLeft',
    path: '/tools/jpg-to-png',
    acceptedFileTypes: '.jpg,.jpeg',
    acceptedMimeTypes: ['image/jpeg'],
    maxFiles: 20,
    seoTitle: 'JPG to PNG Converter – Convert JPG to PNG Free Online | CM DocFlow AI',
    seoDescription: 'Convert JPG to PNG images with crystal clarity and optimal compression. Instant browser conversion.'
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    tagline: 'Convert PNG graphics into lightweight JPG format for fast loading.',
    description: 'Transform large PNG assets into compact JPG files with customizable background color and quality slider.',
    category: 'image',
    categoryLabel: 'Image Tools',
    iconName: 'ArrowRightLeft',
    path: '/tools/png-to-jpg',
    acceptedFileTypes: '.png',
    acceptedMimeTypes: ['image/png'],
    maxFiles: 20,
    seoTitle: 'PNG to JPG Converter – Convert PNG to JPG Online | CM DocFlow AI',
    seoDescription: 'Convert PNG images to JPG format with high compression efficiency and clean background rendering.'
  },
  {
    id: 'webp-to-jpg',
    name: 'WEBP to JPG',
    tagline: 'Convert modern WEBP images back to universal JPG format.',
    description: 'Ensure compatibility with legacy software, email clients, and printing systems by converting WEBP to JPG.',
    category: 'image',
    categoryLabel: 'Image Tools',
    iconName: 'ArrowRightLeft',
    path: '/tools/webp-to-jpg',
    acceptedFileTypes: '.webp',
    acceptedMimeTypes: ['image/webp'],
    maxFiles: 20,
    seoTitle: 'WEBP to JPG Converter – Convert WEBP to JPG Free | CM DocFlow AI',
    seoDescription: 'Fast, secure WEBP to JPG online image converter. Batch convert multiple files with ease.'
  },
  {
    id: 'jpg-to-webp',
    name: 'JPG to WEBP',
    tagline: 'Modernize JPG photos into next-gen WEBP for 30%+ smaller file sizes.',
    description: 'Upgrade your website assets to Google WEBP format for faster page speed and higher Google Core Web Vitals.',
    category: 'image',
    categoryLabel: 'Image Tools',
    iconName: 'Zap',
    path: '/tools/jpg-to-webp',
    acceptedFileTypes: '.jpg,.jpeg',
    acceptedMimeTypes: ['image/jpeg'],
    maxFiles: 20,
    badge: 'Speed Up Web',
    seoTitle: 'JPG to WEBP Converter – Next-Gen Image Conversion | CM DocFlow AI',
    seoDescription: 'Convert JPG photos to modern WEBP format online. Drastically reduce web asset loading times.'
  },
  {
    id: 'png-to-webp',
    name: 'PNG to WEBP',
    tagline: 'Convert transparent PNG files into modern lightweight WEBP format.',
    description: 'Preserve alpha transparency while slashing file sizes by up to 50% compared to traditional PNGs.',
    category: 'image',
    categoryLabel: 'Image Tools',
    iconName: 'Zap',
    path: '/tools/png-to-webp',
    acceptedFileTypes: '.png',
    acceptedMimeTypes: ['image/png'],
    maxFiles: 20,
    seoTitle: 'PNG to WEBP Converter – Convert PNG to WEBP with Alpha | CM DocFlow AI',
    seoDescription: 'Convert transparent PNG images to lightweight WEBP format while retaining crisp edges and alpha channels.'
  },
  {
    id: 'webp-to-png',
    name: 'WEBP to PNG',
    tagline: 'Convert WEBP images to lossless PNG format with transparent alpha.',
    description: 'Extract pristine PNG graphics from WEBP assets for Photoshop, Figma, Illustrator, and editing suites.',
    category: 'image',
    categoryLabel: 'Image Tools',
    iconName: 'ArrowRightLeft',
    path: '/tools/webp-to-png',
    acceptedFileTypes: '.webp',
    acceptedMimeTypes: ['image/webp'],
    maxFiles: 20,
    seoTitle: 'WEBP to PNG Converter – Convert WEBP to PNG Free | CM DocFlow AI',
    seoDescription: 'Convert WEBP to lossless PNG format with transparency intact. Fast, secure in-browser conversion.'
  }
];

export const TOOL_CATEGORIES = [
  { id: 'all', label: 'All Tools' },
  { id: 'pdf', label: 'PDF Utilities' },
  { id: 'conversion', label: 'Document Conversion' },
  { id: 'image', label: 'Image Tools' }
] as const;
